In [2]:
import os
import pandas as pd
import sqlalchemy
from google.auth import default
from google.auth.transport.requests import Request

ModuleNotFoundError: No module named 'google.auth'

In [1]:
from google.cloud.sql.connector import Connector

In [2]:
import os
from google.cloud.sql.connector import Connector
import sqlalchemy
import pandas as pd

# Set the environment variable for authentication
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = r"D:\Courses\Python\Pycharm Fun projects\Streamlit\Streamlit_GCP_SQL\.streamlit\mysql-cloud-427906-9c20e22716fa.json"

# Initialize the connector
connector = Connector()

# Define the connection
def getconn():
    conn = connector.connect(
        "mysql-cloud-427906:asia-south1:cloud-sql-demo",
        "pymysql",
        user="root",
        password="7869816602",
        db="banking_system_project"
    )
    return conn

# Use SQLAlchemy for connection pooling
engine = sqlalchemy.create_engine(
    "mysql+pymysql://",
    creator=getconn
)

# Example: Execute a query and return a DataFrame
def query_to_dataframe(query):
    with engine.connect() as connection:
        result = connection.execute(sqlalchemy.text(query))
        df = pd.DataFrame(result.fetchall(), columns=result.keys())
    return df

# Example usage
df = query_to_dataframe("SELECT * FROM Bank;")
df

   AccountNumber AccountType Account_opening_date CurrentBalance
0     1000000000     Current           2024-06-30       10000.00
1     1000000001       Fixed           2024-06-30       25000.00
2     1000000002     Current           2024-06-30       43147.00
3     1000000003     Current           2024-06-30      122510.00

In [10]:
import os
from google.cloud.sql.connector import Connector
import sqlalchemy
import pandas as pd

# Set the environment variable for authentication
os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = r"D:\Courses\Python\Pycharm Fun projects\Streamlit\Streamlit_GCP_SQL\mysql-cloud-427906-9c20e22716fa.json"

# Initialize the connector
connector = Connector()

# Define the connection
def getconn():
    conn = connector.connect(
        "mysql-cloud-427906:asia-south1:cloud-sql-demo",
        "pymysql",
        user="root",
        password="7869816602",
        db="banking"
    )
    return conn

# Use SQLAlchemy for connection pooling
engine = sqlalchemy.create_engine(
    "mysql+pymysql://",
    creator=getconn
)

# Example: Execute a query and return a DataFrame
def query_to_dataframe(query):
    with engine.connect() as connection:
        result = connection.execute(sqlalchemy.text(query))
        df = pd.DataFrame(result.fetchall(), columns=result.keys())
    return df

# Example usage
df = query_to_dataframe("SELECT * FROM Bank;")
df

   AccountNumber AccountType Account_opening_date CurrentBalance
0     7869816602       Fixed           2024-06-30      548963.00
1     9806220223      Curent           2024-06-30      454688.00
2   901152892993     Savings           2024-06-30     6885684.00

In [4]:
import sqlite3
# from google.cloud import storage
import pandas as pd
import numpy as np
from datetime import datetime
import mysql.connector
import sqlalchemy
import sys

In [ ]:
cnx = mysql.connector.connect(user='root', password='7869816602',
                              host='34.100.194.35',
                              database='banking_system_project')
cursor = cnx.cursor()
query = "SELECT * FROM Bank;"
cursor.execute(query)
result = pd.DataFrame(cursor.fetchall())
result.columns = cursor.column_names 

result # IP Whitelisting Issue.